name: Config
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update

      - name: Run CMake
        run: |
          clang++ -std=c++20 -o hello hello.cpp