name: Config
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Square-Function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Update and Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake
          # Create a directory for building the library files
          mkdir ~/gtest-build
          cd ~/gtest-build
          cmake /usr/src/gtest
          make
          # Copy the library files to /usr/lib
          sudo cp libgtest*.a /usr/lib

      - name: Compile and Run Test for square.h
        run: |
          g++ unit.cpp -I ./include -L . -lgtest -lgtest_main -pthread
          ./a.out

